### PR TITLE
Use custom PDOStatement instead

### LINKED ISSUE #8: Library PDOStatement does not extend extension PDOStatement
Since `\Filisko\PDOplus\PDOStatement` does not extend `\PDOStatement` This library does not work anywhere where parameter types are enforced. This is not a problem with the `PDO` class that follows LSP.

### PR DESCRIPTION
**Pull request by patrickkusebauch**
Resolves #8.

### CODE REVIEW

**Comment by filisko** [comment]
This looks very cool, im going to check it. I read all your comments of the issue but i didn't have time to look at it.

These changes are not backward-compatible, right?

**Comment by patrickkusebauch** [comment]
Well, I see only one instance when it BC breaks. If someone was to check whether the `$statement` produced by the `PDO` class is `instanceof \PDOStatement`. In the old version, it was not inherited from the class, now it is.

**Comment by patrickkusebauch** [comment]
@filisko Is there anything else you need from me with regards to this PR?

**Comment by filisko** [comment]
Checking it now

**Comment by filisko** [comment]
Thank you @patrickkusebauch !! :+1: :tada:

**Pull request merged**
